# Generated by Django 4.1.7 on 2023-02-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('date_create', models.DateField(verbose_name='Data da Criação')),
                ('details', models.CharField(max_length=300, verbose_name='Detalhes')),
                ('photo_art', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y', verbose_name='Foto da Obra')),
            ],
        ),
    ]
